apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Values.eksNamespace }}
spec:
  limits:
  - default:
      memory: "1Gi"
      cpu: "500m"
    defaultRequest:
      memory: "512Mi"
      cpu: "200m"
    type: Container
